# Generated by Django 6.0.8 on 2026-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Телеграмм chat_id"),
        ),
    ]
