# Generated by Django 6.0.8 on 2026-08-18 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=100, verbose_name="Место выполнения привычки")),
                ("date_time", models.DateTimeField(verbose_name="Время выполнения привычки")),
                ("habit", models.CharField(max_length=100, verbose_name="Полезная привычка")),
                ("is_pleasure", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                ("period", models.PositiveIntegerField(default=1, verbose_name="Периодичность выполнения привычки")),
                ("present", models.CharField(blank=True, max_length=100, null=True, verbose_name="Вознаграждение")),
                ("time_habit", models.TimeField(verbose_name="Время на выполнение привычки")),
                ("is_public", models.BooleanField(default=False, verbose_name="Признак публичности")),
                (
                    "connection_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="myhabits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
