# Generated by Django 6.0.8 on 2026-08-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myhabits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="connection_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits",
                to="myhabits.habit",
                verbose_name="Связанная приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasure",
            field=models.BooleanField(blank=True, null=True, verbose_name="Признак приятной привычки"),
        ),
    ]
